### ISSUE TITLE
No way to know which environment generated event in Azure Web Sites

### ISSUE THREAD

**Issue by SergeyKanzhelev** [Microsoft/ApplicationInsights-dotnet-server#248]
In beta4 we used full name with the "slot" name as instance name:

![image](https://cloud.githubusercontent.com/assets/9950081/20853062/5d9dffb6-b89e-11e6-9c22-8bd9c60eeda5.png)

In beta6 we are using hash code of an instance and kept role name to be the role name of the "main" site:

![image](https://cloud.githubusercontent.com/assets/9950081/20853081/81319c1c-b89e-11e6-9ec2-157efd921abe.png)

So now there is no way to know which slot dependency was sent from. Consider adding a custom property or change the role name property

**Comment by cijothomas** [comment]
We might need to use %WEBSITE_HOSTNAME% for Rolename instead of WEBSITE_SITE_NAME, as the former appends the 'slot' name to the sitename.
Following output from production vs dev slot of my webapp

> echo %WEBSITE_HOSTNAME%
D:\home\site\wwwroot
cijo22beta6-dev.azurewebsites.net

> echo %WEBSITE_HOSTNAME%
D:\home\site\wwwroot
cijo22beta6.azurewebsites.net

**Comment by cijothomas** [comment]
%WEBSITE_HOSTNAME% combined with WEBSITE_INSTANCE_ID would be needed. Because HostName alone will not be able to distinguish between instances, and instance_id can't distinguish slots. So a combination should be used.

**Comment by dnduffy** [comment]
Fixed: https://github.com/Microsoft/ApplicationInsights-dotnet-server/pull/250

**Comment by SergeyKanzhelev** [comment]
Ok, the fix was applied to send slot as a nodeName. However nodeName is not exposed neither in UI nor in analytics. So it wasn't really fixed. Consider sending it as a role name instead of a host name

Also `SCM_instance_id` is not used any more. What's the reason? Using instance ID as Azure Web Apps understand it can help correlate telemetry with the azure Web Site telemetry. You can even send a ping to the specific instance of Azure Web Site using arr cookies. Computer name doesn't look like a meaningful choice for Azure Web Apps

**Comment by SergeyKanzhelev** [comment]
@iusafaro can you please comment on this?

**Comment by iusafaro** [comment]
Yes, we're using HostName for NodeName as it contains slot. However ideally we'd like to use instance name, but there's no reliable way to get it - instance ID exposed by Azure Web Apps is tied to computer name and we don't want to over-count nodes as machine can be taken out of rotation and replaced by Azure.

We decided to use machine name for Role Instance Name as it was before to be in consistence with Quick Pulse. Otherwise it's very confusing when you see one metrics reported by machine name and other by instance ID. 

Also I would continue using machine name as it's also used by Azure Web Apps itself when looking at Metrics per instance.

**Comment by SergeyKanzhelev** [comment]
Since NodeName is not exposed in UI - we still need to expose slot somehow. Options are role name or custom property.

**Comment by cijothomas** [comment]
PR : https://github.com/Microsoft/ApplicationInsights-dotnet-server/pull/314
